Repository dmlc/xgboost, pull requests merged in 2020-11, with the labels that each got.

#6333 [dask] Fix prediction on `DaskDMatrix` with multiple meta data.
  python-package/xgboost/dask.py
  tests/python/test_with_dask.py
Labels: Blocking

#6302 Support slicing tree model
  doc/python/callbacks.rst
  doc/python/index.rst
  doc/python/model.rst
  include/xgboost/c_api.h
  include/xgboost/gbm.h
  include/xgboost/learner.h
  python-package/xgboost/callback.py
  python-package/xgboost/core.py
  python-package/xgboost/training.py
  src/c_api/c_api.cc
  src/gbm/gbtree.cc
  src/gbm/gbtree.h
  src/gbm/gbtree_model.cc
  src/gbm/gbtree_model.h
  src/learner.cc
  tests/cpp/gbm/test_gbtree.cc
  tests/cpp/test_learner.cc
  tests/python/test_basic_models.py
  tests/python/test_callback.py
Labels: Blocking

#6362 Support shared library in system path.
  doc/build.rst
  python-package/setup.py
  python-package/xgboost/libpath.py
Labels: Blocking

#6317 Deterministic data partitioning for external memory
  Jenkinsfile-win64
  amalgamation/xgboost-all0.cc
  include/xgboost/data.h
  src/data/data.cc
  src/data/sparse_page_source.cc
  src/data/sparse_page_source.h
  tests/cpp/common/test_column_matrix.cc
  tests/cpp/data/test_data.cc
  tests/cpp/data/test_sparse_page_dmatrix.cc
  tests/cpp/data/test_sparse_page_dmatrix.cu
  tests/cpp/helpers.cc
  tests/cpp/helpers.h
  tests/cpp/predictor/test_cpu_predictor.cc
  tests/cpp/predictor/test_gpu_predictor.cu
  tests/python-gpu/test_gpu_updaters.py
Labels: Blocking

#6371 Run R check as cran on action. [skip ci]
  .github/workflows/main.yml
Labels: Blocking

#6343 [dask] Fix running on k8s.
  python-package/xgboost/dask.py
  tests/python-gpu/test_gpu_with_dask.py
  tests/python/test_tracker.py
  tests/python/test_with_dask.py
Labels: Blocking

#6374 [R] Fix warnings from R check --as-cran
  Makefile
  R-package/R/xgb.ggplot.R
  R-package/R/xgb.plot.shap.R
  R-package/man/xgb.shap.data.Rd
  rabit/include/rabit/internal/utils.h
  rabit/src/allreduce_base.cc
  rabit/src/allreduce_base.h
Labels: Blocking

#6369 Fix plotting.
  src/tree/tree_model.cc
  tests/cpp/tree/test_tree_model.cc
Labels: Blocking

#6378 [R] Fix a crash that occurs with noLD R
  R-package/R/callbacks.R
Labels: Blocking

#6376 Update Python documents.
  demo/guide-python/cross_validation.py
  doc/python/python_api.rst
  python-package/xgboost/sklearn.py
  tests/python/test_callback.py
Labels: Blocking

#6379 [dask] Allow empty data matrix in AFT survival
  src/metric/survival_metric.cu
  tests/python/test_survival.py
  tests/python/test_with_dask.py
Labels: Blocking, dask

#6365 Deprecate positional arguments.
  python-package/xgboost/core.py
  python-package/xgboost/dask.py
  python-package/xgboost/sklearn.py
  tests/python/test_with_sklearn.py
Labels: Blocking

#6375 [dask] Fix union of workers.
  python-package/xgboost/dask.py
  tests/python/test_with_dask.py
Labels: Blocking

#6380 [R] Do not convert continuous labels to factors
  R-package/R/utils.R
  R-package/tests/testthat/test_helpers.R
Labels: Blocking

#6373 [jvm-packages] fix potential unit test suites aborted issue
  jvm-packages/xgboost4j-spark/src/main/scala/org/apache/spark/SparkParallelismTracker.scala
  jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/PerTest.scala
  jvm-packages/xgboost4j-spark/src/test/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRabitRegressionSuite.scala
Labels: Blocking

#6406 [CI] Upgrade to MacOS Mojave image
  .travis.yml
  tests/travis/run_test.sh
Labels: Blocking

#6337 Use pytest conventions consistently
  tests/python-gpu/load_pickle.py
  tests/python-gpu/test_device_quantile_dmatrix.py
  tests/python-gpu/test_gpu_basic_models.py
  tests/python-gpu/test_gpu_interaction_constraints.py
  tests/python-gpu/test_gpu_pickling.py
  tests/python-gpu/test_gpu_prediction.py
  tests/python-gpu/test_gpu_ranking.py
  tests/python-gpu/test_gpu_training_continuation.py
  tests/python-gpu/test_gpu_with_sklearn.py
  tests/python-gpu/test_monotonic_constraints.py
  tests/python/test_basic.py
  tests/python/test_basic_models.py
  tests/python/test_callback.py
  tests/python/test_cli.py
  tests/python/test_dmatrix.py
  tests/python/test_dt.py
  tests/python/test_early_stopping.py
  tests/python/test_eval_metrics.py
  tests/python/test_interaction_constraints.py
  tests/python/test_monotone_constraints.py
  tests/python/test_openmp.py
  tests/python/test_parse_tree.py
  tests/python/test_pickling.py
  tests/python/test_plotting.py
  tests/python/test_predict.py
  tests/python/test_ranking.py
  tests/python/test_shap.py
  tests/python/test_training_continuation.py
  tests/python/test_tree_regularization.py
  tests/python/test_updaters.py
  tests/python/test_with_modin.py
  tests/python/test_with_pandas.py
  tests/python/test_with_sklearn.py
  tests/python/testing.py
Labels: Blocking

#6412 Fix dask predict
  python-package/xgboost/dask.py
Labels: Blocking

#6417 Fix flaky sparse page dmatrix test.
  tests/cpp/data/test_sparse_page_dmatrix.cc
Labels: Blocking

#6403 Fix MPI build.
  rabit/src/engine_mpi.cc
  src/CMakeLists.txt
  tests/distributed/runtests-mpi.sh
  tests/distributed/test_issue3402.py
Labels: Blocking

#6423 [R] Fix R package installation via CMake
  cmake/RPackageInstallTargetSetup.cmake
Labels: Blocking, type: r-package

#6358 Thread local memory allocation for BuildHist
  src/common/hist_util.h
  src/common/row_set.h
  src/tree/updater_quantile_hist.cc
  tests/cpp/common/test_hist_util.cc
  tests/cpp/common/test_partition_builder.cc
  tests/cpp/tree/test_quantile_hist.cc
Labels: Blocking

#6439 Fix CLI ranking demo.
  demo/rank/mq2008.conf
  src/cli_main.cc
  tests/python/test_cli.py
Labels: Blocking

#6441 Fix `period = 1` in evaluation monitor.
  python-package/xgboost/callback.py
  tests/python/test_callback.py
Labels: Blocking
